### ISSUE TITLE
Issue with toolboard

### ISSUE THREAD

**Issue by WartyTowel** [pRINTERnOODLE/Auto-Z-calibration-for-RRF-3.3-or-later-and-Klicky-Probe#2]
Hi,

You use  "M558 P5" in "use_clicky_autoz.g". I recommend to use "P8" here, that makes it compatible for toolboard users.
(Or make it configurable)

Cheers, Chriss

**Comment by pRINTERnOODLE** [comment]
Setting the input type to unfiltered with P8 somehow makes the toolboard responsive? 
Interesting...change committed.

**Comment by WartyTowel** [comment]
Yes.. I use P8 for my clicky on the the toolboards:
M558 P8 H1 A5 S0.003 C"^121.io2.in" F700:120 T8000 B0 R0	

Thanks for the change... I found some other bits pieces, I may come back to you with a pull request if you like some more feedback. ;) 

Cheers, Chriss 
Discord: Chriss#1406

**Comment by pRINTERnOODLE** [comment]
Sure thing!

**Comment by WartyTowel** [comment]
I created a pull request with my changes. I changed the way how you create the variables. I created them now in a separate file in scripts folder (defaults.g) only if they do not exist. I "set" them than in the edit_me.g. The autoz.g will read the new file before the edit_me.g. That makes sure that you can change the variables now without the need to reboot the mainboard. That was a huge problem I was facing when I started to play with it yesterday.

RRF supports not two F values (F240:120). The first number represents the speed for the first run, the second one for all further probe runs.  

Some more tiny changes, I guess that the rest is clear...

Feel free to ping me on discord if you want to discuss.... Chriss#1406

Cheers, Chriss
